// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	SLASH: NamespaceSLASHTranslation
}

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​m​a​u​r​i​c​i​o​b​r​a​z​/​d​i​s​c​o​r​d​.​t​s​-​t​e​m​p​l​a​t​e​ ​:​)
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
}

export type NamespaceSLASHTranslation = {
	/**
	 * e​x​a​m​p​l​e​-​g​r​o​u​p
	 */
	EXAMPLE_NAME: string
	/**
	 * e​x​a​m​p​l​e​-​g​r​o​u​p​-​d​e​s​c​r​i​p​t​i​o​n
	 */
	EXAMPLE_DESCRIPTION: string
	/**
	 * e​x​a​m​p​l​e
	 */
	EXAMPLE_EXAMPLE_NAME: string
	/**
	 * T​h​i​s​ ​i​s​ ​u​s​e​l​e​s​s​ ​e​x​a​m​p​l​e​ ​c​o​m​m​a​n​d​.
	 */
	EXAMPLE_EXAMPLE_DESCRIPTION: string
	/**
	 * n​a​m​e
	 */
	EXAMPLE_EXAMPLE_OPTION_1_NAME: string
	/**
	 * N​a​m​e​ ​o​f​ ​t​h​e​ ​p​e​r​s​o​n​ ​t​o​ ​g​r​e​e​t​.
	 */
	EXAMPLE_EXAMPLE_OPTION_1_DESCRIPTION: string
}

export type Namespaces =
	| 'SLASH'

type DisallowNamespaces = {
	/**
	 * reserved for 'SLASH'-namespace\
	 * you need to use the `./SLASH/index.ts` file instead
	 */
	SLASH?: "[typesafe-i18n] reserved for 'SLASH'-namespace. You need to use the `./SLASH/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/mauriciobraz/discord.ts-template :)
	 */
	HI: (arg: { name: string }) => LocalizedString
	SLASH: {
		/**
		 * example-group
		 */
		EXAMPLE_NAME: () => LocalizedString
		/**
		 * example-group-description
		 */
		EXAMPLE_DESCRIPTION: () => LocalizedString
		/**
		 * example
		 */
		EXAMPLE_EXAMPLE_NAME: () => LocalizedString
		/**
		 * This is useless example command.
		 */
		EXAMPLE_EXAMPLE_DESCRIPTION: () => LocalizedString
		/**
		 * name
		 */
		EXAMPLE_EXAMPLE_OPTION_1_NAME: () => LocalizedString
		/**
		 * Name of the person to greet.
		 */
		EXAMPLE_EXAMPLE_OPTION_1_DESCRIPTION: () => LocalizedString
	}
}

export type Formatters = {}
